# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
import cv2
import numpy as np
from PIL import ImageGrab
import pyautogui
import defs
from mss import mss

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(174, 157)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(90, 100, 75, 31))
        self.btn_start.setObjectName("btn_start")

        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(10, 100, 75, 31))
        self.btn_stop.setObjectName("btn_stop")

        self.btn_guide = QtWidgets.QPushButton(self.centralwidget)
        self.btn_guide.setGeometry(QtCore.QRect(10, 70, 151, 23))
        self.btn_guide.setObjectName("btn_guide")

        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 151, 53))
        self.formLayoutWidget.setObjectName("formLayoutWidget")

        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")

        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)

        self.lbl_status = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_status.setObjectName("lbl_status")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbl_status)

        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)

        self.lbl_trum = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_trum.setObjectName("lbl_trum")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lbl_trum)

        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)

        self.lbl_sum = QtWidgets.QLabel(self.formLayoutWidget)
        self.lbl_sum.setObjectName("lbl_sum")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lbl_sum)

        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")

        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.add_functions()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.btn_start.setText(_translate("MainWindow", "Старт"))

        self.btn_stop.setText(_translate("MainWindow", "Стоп"))

        self.btn_guide.setText(_translate("MainWindow", "Как запускать?"))

        self.label.setText(_translate("MainWindow", "Статус бота:"))

        self.lbl_status.setText(_translate("MainWindow", "Status"))

        self.label_3.setText(_translate("MainWindow", "Трюм:"))

        self.lbl_trum.setText(_translate("MainWindow", "now/max"))

        self.label_5.setText(_translate("MainWindow", "Всего добыто:"))

        self.lbl_sum.setText(_translate("MainWindow", "count"))

    def add_functions(self):
        self.btn_start.clicked.connect(self.click_start)
        self.btn_stop.clicked.connect(self.click_stop)
        self.btn_guide.clicked.connect(self.click_guide)

    def click_start(self):
        status = defs.click_start()
        _translate = QtCore.QCoreApplication.translate
        self.lbl_status.setText(_translate("MainWindow", f"{status}"))

    def click_stop(self):
        print('click_stop')

    def click_guide(self):
        txt = "Это гайд по боту"
        guide_box = QMessageBox()

        guide_box.setWindowTitle("Подсказка")
        guide_box.setText(txt)
        guide_box.setIcon(QMessageBox.Information)

        guide_box.exec_()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
